/* This file contains stub implementations of the AUTOSAR RTE functions.
   The stub implementations can be used for testing the generated code in
   Simulink, for example, in SIL/PIL simulations of the component under
   test. Note that this file should be replaced with an appropriate RTE
   file when deploying the generated code outside of Simulink.

   This file is generated for:
   Atomic software component:  "REL"
   ARXML schema: "4.3"
   File generated on: "06-Sep-2023 14:20:04"  */

#ifndef Rte_REL_h
#define Rte_REL_h
#include "Rte_Type.h"
#include "Compiler.h"

/* Data access functions */
#define Rte_Write_VbOUT_REL_FLDoorMotorA_flg_VbOUT_REL_FLDoorMotorA_flg Rte_Write_REL_VbOUT_REL_FLDoorMotorA_flg_VbOUT_REL_FLDoorMotorA_flg

Std_ReturnType Rte_Write_VbOUT_REL_FLDoorMotorA_flg_VbOUT_REL_FLDoorMotorA_flg
  (Boolean u);

#define Rte_Invalidate_VbOUT_REL_FLDoorMotorA_flg_VbOUT_REL_FLDoorMotorA_flg Rte_Invalidate_REL_VbOUT_REL_FLDoorMotorA_flg_VbOUT_REL_FLDoorMotorA_flg

Std_ReturnType
  Rte_Invalidate_VbOUT_REL_FLDoorMotorA_flg_VbOUT_REL_FLDoorMotorA_flg(void);

#define Rte_Write_VbOUT_REL_FLDoorMotorB_flg_VbOUT_REL_FLDoorMotorB_flg Rte_Write_REL_VbOUT_REL_FLDoorMotorB_flg_VbOUT_REL_FLDoorMotorB_flg

Std_ReturnType Rte_Write_VbOUT_REL_FLDoorMotorB_flg_VbOUT_REL_FLDoorMotorB_flg
  (Boolean u);

#define Rte_Invalidate_VbOUT_REL_FLDoorMotorB_flg_VbOUT_REL_FLDoorMotorB_flg Rte_Invalidate_REL_VbOUT_REL_FLDoorMotorB_flg_VbOUT_REL_FLDoorMotorB_flg

Std_ReturnType
  Rte_Invalidate_VbOUT_REL_FLDoorMotorB_flg_VbOUT_REL_FLDoorMotorB_flg(void);

#define Rte_Write_VbOUT_REL_FRDoorMotorA_flg_VbOUT_REL_FRDoorMotorA_flg Rte_Write_REL_VbOUT_REL_FRDoorMotorA_flg_VbOUT_REL_FRDoorMotorA_flg

Std_ReturnType Rte_Write_VbOUT_REL_FRDoorMotorA_flg_VbOUT_REL_FRDoorMotorA_flg
  (Boolean u);

#define Rte_Invalidate_VbOUT_REL_FRDoorMotorA_flg_VbOUT_REL_FRDoorMotorA_flg Rte_Invalidate_REL_VbOUT_REL_FRDoorMotorA_flg_VbOUT_REL_FRDoorMotorA_flg

Std_ReturnType
  Rte_Invalidate_VbOUT_REL_FRDoorMotorA_flg_VbOUT_REL_FRDoorMotorA_flg(void);

#define Rte_Write_VbOUT_REL_FRDoorMotorB_flg_VbOUT_REL_FRDoorMotorB_flg Rte_Write_REL_VbOUT_REL_FRDoorMotorB_flg_VbOUT_REL_FRDoorMotorB_flg

Std_ReturnType Rte_Write_VbOUT_REL_FRDoorMotorB_flg_VbOUT_REL_FRDoorMotorB_flg
  (Boolean u);

#define Rte_Invalidate_VbOUT_REL_FRDoorMotorB_flg_VbOUT_REL_FRDoorMotorB_flg Rte_Invalidate_REL_VbOUT_REL_FRDoorMotorB_flg_VbOUT_REL_FRDoorMotorB_flg

Std_ReturnType
  Rte_Invalidate_VbOUT_REL_FRDoorMotorB_flg_VbOUT_REL_FRDoorMotorB_flg(void);

#define Rte_Write_VbOUT_REL_RLDoorMotorA_flg_VbOUT_REL_RLDoorMotorA_flg Rte_Write_REL_VbOUT_REL_RLDoorMotorA_flg_VbOUT_REL_RLDoorMotorA_flg

Std_ReturnType Rte_Write_VbOUT_REL_RLDoorMotorA_flg_VbOUT_REL_RLDoorMotorA_flg
  (Boolean u);

#define Rte_Invalidate_VbOUT_REL_RLDoorMotorA_flg_VbOUT_REL_RLDoorMotorA_flg Rte_Invalidate_REL_VbOUT_REL_RLDoorMotorA_flg_VbOUT_REL_RLDoorMotorA_flg

Std_ReturnType
  Rte_Invalidate_VbOUT_REL_RLDoorMotorA_flg_VbOUT_REL_RLDoorMotorA_flg(void);

#define Rte_Write_VbOUT_REL_RLDoorMotorB_flg_VbOUT_REL_RLDoorMotorB_flg Rte_Write_REL_VbOUT_REL_RLDoorMotorB_flg_VbOUT_REL_RLDoorMotorB_flg

Std_ReturnType Rte_Write_VbOUT_REL_RLDoorMotorB_flg_VbOUT_REL_RLDoorMotorB_flg
  (Boolean u);

#define Rte_Invalidate_VbOUT_REL_RLDoorMotorB_flg_VbOUT_REL_RLDoorMotorB_flg Rte_Invalidate_REL_VbOUT_REL_RLDoorMotorB_flg_VbOUT_REL_RLDoorMotorB_flg

Std_ReturnType
  Rte_Invalidate_VbOUT_REL_RLDoorMotorB_flg_VbOUT_REL_RLDoorMotorB_flg(void);

#define Rte_Write_VbOUT_REL_RRDoorMotorA_flg_VbOUT_REL_RRDoorMotorA_flg Rte_Write_REL_VbOUT_REL_RRDoorMotorA_flg_VbOUT_REL_RRDoorMotorA_flg

Std_ReturnType Rte_Write_VbOUT_REL_RRDoorMotorA_flg_VbOUT_REL_RRDoorMotorA_flg
  (Boolean u);

#define Rte_Invalidate_VbOUT_REL_RRDoorMotorA_flg_VbOUT_REL_RRDoorMotorA_flg Rte_Invalidate_REL_VbOUT_REL_RRDoorMotorA_flg_VbOUT_REL_RRDoorMotorA_flg

Std_ReturnType
  Rte_Invalidate_VbOUT_REL_RRDoorMotorA_flg_VbOUT_REL_RRDoorMotorA_flg(void);

#define Rte_Write_VbOUT_REL_RRDoorMotorB_flg_VbOUT_REL_RRDoorMotorB_flg Rte_Write_REL_VbOUT_REL_RRDoorMotorB_flg_VbOUT_REL_RRDoorMotorB_flg

Std_ReturnType Rte_Write_VbOUT_REL_RRDoorMotorB_flg_VbOUT_REL_RRDoorMotorB_flg
  (Boolean u);

#define Rte_Invalidate_VbOUT_REL_RRDoorMotorB_flg_VbOUT_REL_RRDoorMotorB_flg Rte_Invalidate_REL_VbOUT_REL_RRDoorMotorB_flg_VbOUT_REL_RRDoorMotorB_flg

Std_ReturnType
  Rte_Invalidate_VbOUT_REL_RRDoorMotorB_flg_VbOUT_REL_RRDoorMotorB_flg(void);

#define Rte_Write_VbOUT_REL_RLDoorRlsReq_flg_VbOUT_REL_RLDoorRlsReq_flg Rte_Write_REL_VbOUT_REL_RLDoorRlsReq_flg_VbOUT_REL_RLDoorRlsReq_flg

Std_ReturnType Rte_Write_VbOUT_REL_RLDoorRlsReq_flg_VbOUT_REL_RLDoorRlsReq_flg
  (Boolean u);

#define Rte_Invalidate_VbOUT_REL_RLDoorRlsReq_flg_VbOUT_REL_RLDoorRlsReq_flg Rte_Invalidate_REL_VbOUT_REL_RLDoorRlsReq_flg_VbOUT_REL_RLDoorRlsReq_flg

Std_ReturnType
  Rte_Invalidate_VbOUT_REL_RLDoorRlsReq_flg_VbOUT_REL_RLDoorRlsReq_flg(void);

#define Rte_Write_VbOUT_REL_RRDoorRlsReq_flg_VbOUT_REL_RRDoorRlsReq_flg Rte_Write_REL_VbOUT_REL_RRDoorRlsReq_flg_VbOUT_REL_RRDoorRlsReq_flg

Std_ReturnType Rte_Write_VbOUT_REL_RRDoorRlsReq_flg_VbOUT_REL_RRDoorRlsReq_flg
  (Boolean u);

#define Rte_Invalidate_VbOUT_REL_RRDoorRlsReq_flg_VbOUT_REL_RRDoorRlsReq_flg Rte_Invalidate_REL_VbOUT_REL_RRDoorRlsReq_flg_VbOUT_REL_RRDoorRlsReq_flg

Std_ReturnType
  Rte_Invalidate_VbOUT_REL_RRDoorRlsReq_flg_VbOUT_REL_RRDoorRlsReq_flg(void);

#define Rte_Write_VeOUT_REL_FLDoorMotorSts_sig_VeOUT_REL_FLDoorMotorSts_sig Rte_Write_REL_VeOUT_REL_FLDoorMotorSts_sig_VeOUT_REL_FLDoorMotorSts_sig

Std_ReturnType
  Rte_Write_VeOUT_REL_FLDoorMotorSts_sig_VeOUT_REL_FLDoorMotorSts_sig(UInt8 u);

#define Rte_Invalidate_VeOUT_REL_FLDoorMotorSts_sig_VeOUT_REL_FLDoorMotorSts_sig Rte_Invalidate_REL_VeOUT_REL_FLDoorMotorSts_sig_VeOUT_REL_FLDoorMotorSts_sig

Std_ReturnType
  Rte_Invalidate_VeOUT_REL_FLDoorMotorSts_sig_VeOUT_REL_FLDoorMotorSts_sig(void);

#define Rte_Write_VeOUT_REL_FRDoorMotorSts_sig_VeOUT_REL_FRDoorMotorSts_sig Rte_Write_REL_VeOUT_REL_FRDoorMotorSts_sig_VeOUT_REL_FRDoorMotorSts_sig

Std_ReturnType
  Rte_Write_VeOUT_REL_FRDoorMotorSts_sig_VeOUT_REL_FRDoorMotorSts_sig(UInt8 u);

#define Rte_Invalidate_VeOUT_REL_FRDoorMotorSts_sig_VeOUT_REL_FRDoorMotorSts_sig Rte_Invalidate_REL_VeOUT_REL_FRDoorMotorSts_sig_VeOUT_REL_FRDoorMotorSts_sig

Std_ReturnType
  Rte_Invalidate_VeOUT_REL_FRDoorMotorSts_sig_VeOUT_REL_FRDoorMotorSts_sig(void);

#define Rte_Write_VeOUT_REL_RLDoorMotorSts_sig_VeOUT_REL_RLDoorMotorSts_sig Rte_Write_REL_VeOUT_REL_RLDoorMotorSts_sig_VeOUT_REL_RLDoorMotorSts_sig

Std_ReturnType
  Rte_Write_VeOUT_REL_RLDoorMotorSts_sig_VeOUT_REL_RLDoorMotorSts_sig(UInt8 u);

#define Rte_Invalidate_VeOUT_REL_RLDoorMotorSts_sig_VeOUT_REL_RLDoorMotorSts_sig Rte_Invalidate_REL_VeOUT_REL_RLDoorMotorSts_sig_VeOUT_REL_RLDoorMotorSts_sig

Std_ReturnType
  Rte_Invalidate_VeOUT_REL_RLDoorMotorSts_sig_VeOUT_REL_RLDoorMotorSts_sig(void);

#define Rte_Write_VeOUT_REL_RRDoorMotorSts_sig_VeOUT_REL_RRDoorMotorSts_sig Rte_Write_REL_VeOUT_REL_RRDoorMotorSts_sig_VeOUT_REL_RRDoorMotorSts_sig

Std_ReturnType
  Rte_Write_VeOUT_REL_RRDoorMotorSts_sig_VeOUT_REL_RRDoorMotorSts_sig(UInt8 u);

#define Rte_Invalidate_VeOUT_REL_RRDoorMotorSts_sig_VeOUT_REL_RRDoorMotorSts_sig Rte_Invalidate_REL_VeOUT_REL_RRDoorMotorSts_sig_VeOUT_REL_RRDoorMotorSts_sig

Std_ReturnType
  Rte_Invalidate_VeOUT_REL_RRDoorMotorSts_sig_VeOUT_REL_RRDoorMotorSts_sig(void);

#define Rte_Read_VbINP_CAN_CdcAllDoorOpenButtonSts_flg_VbINP_CAN_CdcAllDoorOpenButtonSts_flg Rte_Read_REL_VbINP_CAN_CdcAllDoorOpenButtonSts_flg_VbINP_CAN_CdcAllDoorOpenButtonSts_flg

Std_ReturnType
  Rte_Read_VbINP_CAN_CdcAllDoorOpenButtonSts_flg_VbINP_CAN_CdcAllDoorOpenButtonSts_flg
  (Boolean* u);

#define Rte_Read_VbINP_CAN_CdcDrvrDoorButtonSts_flg_VbINP_CAN_CdcDrvrDoorButtonSts_flg Rte_Read_REL_VbINP_CAN_CdcDrvrDoorButtonSts_flg_VbINP_CAN_CdcDrvrDoorButtonSts_flg

Std_ReturnType
  Rte_Read_VbINP_CAN_CdcDrvrDoorButtonSts_flg_VbINP_CAN_CdcDrvrDoorButtonSts_flg
  (Boolean* u);

#define Rte_Read_VbINP_CAN_CdcLeReDoorButtonSts_flg_VbINP_CAN_CdcLeReDoorButtonSts_flg Rte_Read_REL_VbINP_CAN_CdcLeReDoorButtonSts_flg_VbINP_CAN_CdcLeReDoorButtonSts_flg

Std_ReturnType
  Rte_Read_VbINP_CAN_CdcLeReDoorButtonSts_flg_VbINP_CAN_CdcLeReDoorButtonSts_flg
  (Boolean* u);

#define Rte_Read_VbINP_CAN_CdcPassDoorButtonSts_flg_VbINP_CAN_CdcPassDoorButtonSts_flg Rte_Read_REL_VbINP_CAN_CdcPassDoorButtonSts_flg_VbINP_CAN_CdcPassDoorButtonSts_flg

Std_ReturnType
  Rte_Read_VbINP_CAN_CdcPassDoorButtonSts_flg_VbINP_CAN_CdcPassDoorButtonSts_flg
  (Boolean* u);

#define Rte_Read_VbINP_CAN_CdcRiReDoorButtonSts_flg_VbINP_CAN_CdcRiReDoorButtonSts_flg Rte_Read_REL_VbINP_CAN_CdcRiReDoorButtonSts_flg_VbINP_CAN_CdcRiReDoorButtonSts_flg

Std_ReturnType
  Rte_Read_VbINP_CAN_CdcRiReDoorButtonSts_flg_VbINP_CAN_CdcRiReDoorButtonSts_flg
  (Boolean* u);

#define Rte_Read_VbINP_CAN_EspVehSpdVld_flg_VbINP_CAN_EspVehSpdVld_flg Rte_Read_REL_VbINP_CAN_EspVehSpdVld_flg_VbINP_CAN_EspVehSpdVld_flg

Std_ReturnType Rte_Read_VbINP_CAN_EspVehSpdVld_flg_VbINP_CAN_EspVehSpdVld_flg
  (Boolean* u);

#define Rte_Read_VbINP_CAN_FLDCUCinchHomeSwitch_flg_VbINP_CAN_FLDCUCinchHomeSwitch_flg Rte_Read_REL_VbINP_CAN_FLDCUCinchHomeSwitch_flg_VbINP_CAN_FLDCUCinchHomeSwitch_flg

Std_ReturnType
  Rte_Read_VbINP_CAN_FLDCUCinchHomeSwitch_flg_VbINP_CAN_FLDCUCinchHomeSwitch_flg
  (Boolean* u);

#define Rte_Read_VbINP_CAN_FRDCUCinchHomeSwitch_flg_VbINP_CAN_FRDCUCinchHomeSwitch_flg Rte_Read_REL_VbINP_CAN_FRDCUCinchHomeSwitch_flg_VbINP_CAN_FRDCUCinchHomeSwitch_flg

Std_ReturnType
  Rte_Read_VbINP_CAN_FRDCUCinchHomeSwitch_flg_VbINP_CAN_FRDCUCinchHomeSwitch_flg
  (Boolean* u);

#define Rte_Read_VbINP_CAN_RLDCUCinchHomeSwitch_flg_VbINP_CAN_RLDCUCinchHomeSwitch_flg Rte_Read_REL_VbINP_CAN_RLDCUCinchHomeSwitch_flg_VbINP_CAN_RLDCUCinchHomeSwitch_flg

Std_ReturnType
  Rte_Read_VbINP_CAN_RLDCUCinchHomeSwitch_flg_VbINP_CAN_RLDCUCinchHomeSwitch_flg
  (Boolean* u);

#define Rte_Read_VbINP_CAN_RRDCUCinchHomeSwitch_flg_VbINP_CAN_RRDCUCinchHomeSwitch_flg Rte_Read_REL_VbINP_CAN_RRDCUCinchHomeSwitch_flg_VbINP_CAN_RRDCUCinchHomeSwitch_flg

Std_ReturnType
  Rte_Read_VbINP_CAN_RRDCUCinchHomeSwitch_flg_VbINP_CAN_RRDCUCinchHomeSwitch_flg
  (Boolean* u);

#define Rte_Read_VbINP_CFG_ElectricalDoorCfg_flg_VbINP_CFG_ElectricalDoorCfg_flg Rte_Read_REL_VbINP_CFG_ElectricalDoorCfg_flg_VbINP_CFG_ElectricalDoorCfg_flg

Std_ReturnType
  Rte_Read_VbINP_CFG_ElectricalDoorCfg_flg_VbINP_CFG_ElectricalDoorCfg_flg
  (Boolean* u);

#define Rte_Read_VbINP_HWA_FLDoorAjar_flg_VbINP_HWA_FLDoorAjar_flg Rte_Read_REL_VbINP_HWA_FLDoorAjar_flg_VbINP_HWA_FLDoorAjar_flg

Std_ReturnType Rte_Read_VbINP_HWA_FLDoorAjar_flg_VbINP_HWA_FLDoorAjar_flg
  (Boolean* u);

#define Rte_Read_VbINP_HWA_FLDoorButton_flg_VbINP_HWA_FLDoorButton_flg Rte_Read_REL_VbINP_HWA_FLDoorButton_flg_VbINP_HWA_FLDoorButton_flg

Std_ReturnType Rte_Read_VbINP_HWA_FLDoorButton_flg_VbINP_HWA_FLDoorButton_flg
  (Boolean* u);

#define Rte_Read_VbINP_HWA_FLDoorHandleSW_flg_VbINP_HWA_FLDoorHandleSW_flg Rte_Read_REL_VbINP_HWA_FLDoorHandleSW_flg_VbINP_HWA_FLDoorHandleSW_flg

Std_ReturnType
  Rte_Read_VbINP_HWA_FLDoorHandleSW_flg_VbINP_HWA_FLDoorHandleSW_flg(Boolean* u);

#define Rte_Read_VbINP_HWA_FLDoorOutButton_flg_VbINP_HWA_FLDoorOutButton_flg Rte_Read_REL_VbINP_HWA_FLDoorOutButton_flg_VbINP_HWA_FLDoorOutButton_flg

Std_ReturnType
  Rte_Read_VbINP_HWA_FLDoorOutButton_flg_VbINP_HWA_FLDoorOutButton_flg(Boolean*
  u);

#define Rte_Read_VbINP_HWA_FRDoorAjar_flg_VbINP_HWA_FRDoorAjar_flg Rte_Read_REL_VbINP_HWA_FRDoorAjar_flg_VbINP_HWA_FRDoorAjar_flg

Std_ReturnType Rte_Read_VbINP_HWA_FRDoorAjar_flg_VbINP_HWA_FRDoorAjar_flg
  (Boolean* u);

#define Rte_Read_VbINP_HWA_FRDoorButton_flg_VbINP_HWA_FRDoorButton_flg Rte_Read_REL_VbINP_HWA_FRDoorButton_flg_VbINP_HWA_FRDoorButton_flg

Std_ReturnType Rte_Read_VbINP_HWA_FRDoorButton_flg_VbINP_HWA_FRDoorButton_flg
  (Boolean* u);

#define Rte_Read_VbINP_HWA_FRDoorHandleSW_flg_VbINP_HWA_FRDoorHandleSW_flg Rte_Read_REL_VbINP_HWA_FRDoorHandleSW_flg_VbINP_HWA_FRDoorHandleSW_flg

Std_ReturnType
  Rte_Read_VbINP_HWA_FRDoorHandleSW_flg_VbINP_HWA_FRDoorHandleSW_flg(Boolean* u);

#define Rte_Read_VbINP_HWA_FRDoorOutButton_flg_VbINP_HWA_FRDoorOutButton_flg Rte_Read_REL_VbINP_HWA_FRDoorOutButton_flg_VbINP_HWA_FRDoorOutButton_flg

Std_ReturnType
  Rte_Read_VbINP_HWA_FRDoorOutButton_flg_VbINP_HWA_FRDoorOutButton_flg(Boolean*
  u);

#define Rte_Read_VbINP_HWA_LRChildLckSt_flg_VbINP_HWA_LRChildLckSt_flg Rte_Read_REL_VbINP_HWA_LRChildLckSt_flg_VbINP_HWA_LRChildLckSt_flg

Std_ReturnType Rte_Read_VbINP_HWA_LRChildLckSt_flg_VbINP_HWA_LRChildLckSt_flg
  (Boolean* u);

#define Rte_Read_VbINP_HWA_RLDoorAjar_flg_VbINP_HWA_RLDoorAjar_flg Rte_Read_REL_VbINP_HWA_RLDoorAjar_flg_VbINP_HWA_RLDoorAjar_flg

Std_ReturnType Rte_Read_VbINP_HWA_RLDoorAjar_flg_VbINP_HWA_RLDoorAjar_flg
  (Boolean* u);

#define Rte_Read_VbINP_HWA_RLDoorButton_flg_VbINP_HWA_RLDoorButton_flg Rte_Read_REL_VbINP_HWA_RLDoorButton_flg_VbINP_HWA_RLDoorButton_flg

Std_ReturnType Rte_Read_VbINP_HWA_RLDoorButton_flg_VbINP_HWA_RLDoorButton_flg
  (Boolean* u);

#define Rte_Read_VbINP_HWA_RLDoorHandleSW_flg_VbINP_HWA_RLDoorHandleSW_flg Rte_Read_REL_VbINP_HWA_RLDoorHandleSW_flg_VbINP_HWA_RLDoorHandleSW_flg

Std_ReturnType
  Rte_Read_VbINP_HWA_RLDoorHandleSW_flg_VbINP_HWA_RLDoorHandleSW_flg(Boolean* u);

#define Rte_Read_VbINP_HWA_RLDoorOutButton_flg_VbINP_HWA_RLDoorOutButton_flg Rte_Read_REL_VbINP_HWA_RLDoorOutButton_flg_VbINP_HWA_RLDoorOutButton_flg

Std_ReturnType
  Rte_Read_VbINP_HWA_RLDoorOutButton_flg_VbINP_HWA_RLDoorOutButton_flg(Boolean*
  u);

#define Rte_Read_VbINP_HWA_RRChildLckSt_flg_VbINP_HWA_RRChildLckSt_flg Rte_Read_REL_VbINP_HWA_RRChildLckSt_flg_VbINP_HWA_RRChildLckSt_flg

Std_ReturnType Rte_Read_VbINP_HWA_RRChildLckSt_flg_VbINP_HWA_RRChildLckSt_flg
  (Boolean* u);

#define Rte_Read_VbINP_HWA_RRDoorAjar_flg_VbINP_HWA_RRDoorAjar_flg Rte_Read_REL_VbINP_HWA_RRDoorAjar_flg_VbINP_HWA_RRDoorAjar_flg

Std_ReturnType Rte_Read_VbINP_HWA_RRDoorAjar_flg_VbINP_HWA_RRDoorAjar_flg
  (Boolean* u);

#define Rte_Read_VbINP_HWA_RRDoorButton_flg_VbINP_HWA_RRDoorButton_flg Rte_Read_REL_VbINP_HWA_RRDoorButton_flg_VbINP_HWA_RRDoorButton_flg

Std_ReturnType Rte_Read_VbINP_HWA_RRDoorButton_flg_VbINP_HWA_RRDoorButton_flg
  (Boolean* u);

#define Rte_Read_VbINP_HWA_RRDoorHandleSW_flg_VbINP_HWA_RRDoorHandleSW_flg Rte_Read_REL_VbINP_HWA_RRDoorHandleSW_flg_VbINP_HWA_RRDoorHandleSW_flg

Std_ReturnType
  Rte_Read_VbINP_HWA_RRDoorHandleSW_flg_VbINP_HWA_RRDoorHandleSW_flg(Boolean* u);

#define Rte_Read_VbINP_HWA_RRDoorOutButton_flg_VbINP_HWA_RRDoorOutButton_flg Rte_Read_REL_VbINP_HWA_RRDoorOutButton_flg_VbINP_HWA_RRDoorOutButton_flg

Std_ReturnType
  Rte_Read_VbINP_HWA_RRDoorOutButton_flg_VbINP_HWA_RRDoorOutButton_flg(Boolean*
  u);

#define Rte_Read_VbOUT_SP_CrashOutpSts_flg_VbOUT_SP_CrashOutpSts_flg Rte_Read_REL_VbOUT_SP_CrashOutpSts_flg_VbOUT_SP_CrashOutpSts_flg

Std_ReturnType Rte_Read_VbOUT_SP_CrashOutpSts_flg_VbOUT_SP_CrashOutpSts_flg
  (Boolean* u);

#define Rte_Read_VeINP_CAN_CdcDrvrDoorLockSet_sig_VeINP_CAN_CdcDrvrDoorLockSet_sig Rte_Read_REL_VeINP_CAN_CdcDrvrDoorLockSet_sig_VeINP_CAN_CdcDrvrDoorLockSet_sig

Std_ReturnType
  Rte_Read_VeINP_CAN_CdcDrvrDoorLockSet_sig_VeINP_CAN_CdcDrvrDoorLockSet_sig
  (UInt8* u);

#define Rte_Read_VeINP_CAN_VcuGearPosn_sig_VeINP_CAN_VcuGearPosn_sig Rte_Read_REL_VeINP_CAN_VcuGearPosn_sig_VeINP_CAN_VcuGearPosn_sig

Std_ReturnType Rte_Read_VeINP_CAN_VcuGearPosn_sig_VeINP_CAN_VcuGearPosn_sig
  (UInt8* u);

#define Rte_Read_VeINP_EPRM_BdcDrvrDoorLockSetSts_sig_VeINP_EPRM_BdcDrvrDoorLockSetSts_sig Rte_Read_REL_VeINP_EPRM_BdcDrvrDoorLockSetSts_sig_VeINP_EPRM_BdcDrvrDoorLockSetSts_sig

Std_ReturnType
  Rte_Read_VeINP_EPRM_BdcDrvrDoorLockSetSts_sig_VeINP_EPRM_BdcDrvrDoorLockSetSts_sig
  (UInt8* u);

#define Rte_Read_VeOUT_DHM_BDCDrvrDoorHndSts_sig_VeOUT_DHM_BDCDrvrDoorHndSts_sig Rte_Read_REL_VeOUT_DHM_BDCDrvrDoorHndSts_sig_VeOUT_DHM_BDCDrvrDoorHndSts_sig

Std_ReturnType
  Rte_Read_VeOUT_DHM_BDCDrvrDoorHndSts_sig_VeOUT_DHM_BDCDrvrDoorHndSts_sig(UInt8*
  u);

#define Rte_Read_VeOUT_DHM_BDCLeReDoorHndSts_sig_VeOUT_DHM_BDCLeReDoorHndSts_sig Rte_Read_REL_VeOUT_DHM_BDCLeReDoorHndSts_sig_VeOUT_DHM_BDCLeReDoorHndSts_sig

Std_ReturnType
  Rte_Read_VeOUT_DHM_BDCLeReDoorHndSts_sig_VeOUT_DHM_BDCLeReDoorHndSts_sig(UInt8*
  u);

#define Rte_Read_VeOUT_DHM_BDCPassDoorHndSts_sig_VeOUT_DHM_BDCPassDoorHndSts_sig Rte_Read_REL_VeOUT_DHM_BDCPassDoorHndSts_sig_VeOUT_DHM_BDCPassDoorHndSts_sig

Std_ReturnType
  Rte_Read_VeOUT_DHM_BDCPassDoorHndSts_sig_VeOUT_DHM_BDCPassDoorHndSts_sig(UInt8*
  u);

#define Rte_Read_VeOUT_DHM_BDCRiReDoorHndSts_sig_VeOUT_DHM_BDCRiReDoorHndSts_sig Rte_Read_REL_VeOUT_DHM_BDCRiReDoorHndSts_sig_VeOUT_DHM_BDCRiReDoorHndSts_sig

Std_ReturnType
  Rte_Read_VeOUT_DHM_BDCRiReDoorHndSts_sig_VeOUT_DHM_BDCRiReDoorHndSts_sig(UInt8*
  u);

#define Rte_Read_VeOUT_DLK_BCMPassengerDoorLockStatus_sig_VeOUT_DLK_BCMPassengerDoorLockStatus_sig Rte_Read_REL_VeOUT_DLK_BCMPassengerDoorLockStatus_sig_VeOUT_DLK_BCMPassengerDoorLockStatus_sig

Std_ReturnType
  Rte_Read_VeOUT_DLK_BCMPassengerDoorLockStatus_sig_VeOUT_DLK_BCMPassengerDoorLockStatus_sig
  (UInt8* u);

#define Rte_Read_VeOUT_DLK_BdcDrvrDoorLockSts_sig_VeOUT_DLK_BdcDrvrDoorLockSts_sig Rte_Read_REL_VeOUT_DLK_BdcDrvrDoorLockSts_sig_VeOUT_DLK_BdcDrvrDoorLockSts_sig

Std_ReturnType
  Rte_Read_VeOUT_DLK_BdcDrvrDoorLockSts_sig_VeOUT_DLK_BdcDrvrDoorLockSts_sig
  (UInt8* u);

#define Rte_Read_VeOUT_PDU_BcmPowerStatusFeedback_sig_VeOUT_PDU_BcmPowerStatusFeedback_sig Rte_Read_REL_VeOUT_PDU_BcmPowerStatusFeedback_sig_VeOUT_PDU_BcmPowerStatusFeedback_sig

Std_ReturnType
  Rte_Read_VeOUT_PDU_BcmPowerStatusFeedback_sig_VeOUT_PDU_BcmPowerStatusFeedback_sig
  (UInt8* u);

#define Rte_Read_VeOUT_SP_EspVehSpd_kmh_VeOUT_SP_EspVehSpd_kmh Rte_Read_REL_VeOUT_SP_EspVehSpd_kmh_VeOUT_SP_EspVehSpd_kmh

Std_ReturnType Rte_Read_VeOUT_SP_EspVehSpd_kmh_VeOUT_SP_EspVehSpd_kmh(UInt8* u);

#define Rte_Write_VbOUT_REL_BdcDrvrDoorLockSetSts_flg_VbOUT_REL_BdcDrvrDoorLockSetSts_flg Rte_Write_REL_VbOUT_REL_BdcDrvrDoorLockSetSts_flg_VbOUT_REL_BdcDrvrDoorLockSetSts_flg

Std_ReturnType
  Rte_Write_VbOUT_REL_BdcDrvrDoorLockSetSts_flg_VbOUT_REL_BdcDrvrDoorLockSetSts_flg
  (Boolean u);

#define Rte_Invalidate_VbOUT_REL_BdcDrvrDoorLockSetSts_flg_VbOUT_REL_BdcDrvrDoorLockSetSts_flg Rte_Invalidate_REL_VbOUT_REL_BdcDrvrDoorLockSetSts_flg_VbOUT_REL_BdcDrvrDoorLockSetSts_flg

Std_ReturnType
  Rte_Invalidate_VbOUT_REL_BdcDrvrDoorLockSetSts_flg_VbOUT_REL_BdcDrvrDoorLockSetSts_flg
  (void);

#define Rte_Write_VbOUT_REL_BcmAutoHeadLiSetStsToEE_flg_VbOUT_REL_BcmAutoHeadLiSetStsToEE_flg Rte_Write_REL_VbOUT_REL_BcmAutoHeadLiSetStsToEE_flg_VbOUT_REL_BcmAutoHeadLiSetStsToEE_flg

Std_ReturnType
  Rte_Write_VbOUT_REL_BcmAutoHeadLiSetStsToEE_flg_VbOUT_REL_BcmAutoHeadLiSetStsToEE_flg
  (Boolean u);

#define Rte_Invalidate_VbOUT_REL_BcmAutoHeadLiSetStsToEE_flg_VbOUT_REL_BcmAutoHeadLiSetStsToEE_flg Rte_Invalidate_REL_VbOUT_REL_BcmAutoHeadLiSetStsToEE_flg_VbOUT_REL_BcmAutoHeadLiSetStsToEE_flg

Std_ReturnType
  Rte_Invalidate_VbOUT_REL_BcmAutoHeadLiSetStsToEE_flg_VbOUT_REL_BcmAutoHeadLiSetStsToEE_flg
  (void);

#define Rte_Write_VeOUT_REL_BcmDrvrDoorSwtSts_sig_VeOUT_REL_BcmDrvrDoorSwtSts_sig Rte_Write_REL_VeOUT_REL_BcmDrvrDoorSwtSts_sig_VeOUT_REL_BcmDrvrDoorSwtSts_sig

Std_ReturnType
  Rte_Write_VeOUT_REL_BcmDrvrDoorSwtSts_sig_VeOUT_REL_BcmDrvrDoorSwtSts_sig
  (UInt8 u);

#define Rte_Invalidate_VeOUT_REL_BcmDrvrDoorSwtSts_sig_VeOUT_REL_BcmDrvrDoorSwtSts_sig Rte_Invalidate_REL_VeOUT_REL_BcmDrvrDoorSwtSts_sig_VeOUT_REL_BcmDrvrDoorSwtSts_sig

Std_ReturnType
  Rte_Invalidate_VeOUT_REL_BcmDrvrDoorSwtSts_sig_VeOUT_REL_BcmDrvrDoorSwtSts_sig
  (void);

#define Rte_Write_VeOUT_REL_BcmPassDoorSwtSts_sig_VeOUT_REL_BcmPassDoorSwtSts_sig Rte_Write_REL_VeOUT_REL_BcmPassDoorSwtSts_sig_VeOUT_REL_BcmPassDoorSwtSts_sig

Std_ReturnType
  Rte_Write_VeOUT_REL_BcmPassDoorSwtSts_sig_VeOUT_REL_BcmPassDoorSwtSts_sig
  (UInt8 u);

#define Rte_Invalidate_VeOUT_REL_BcmPassDoorSwtSts_sig_VeOUT_REL_BcmPassDoorSwtSts_sig Rte_Invalidate_REL_VeOUT_REL_BcmPassDoorSwtSts_sig_VeOUT_REL_BcmPassDoorSwtSts_sig

Std_ReturnType
  Rte_Invalidate_VeOUT_REL_BcmPassDoorSwtSts_sig_VeOUT_REL_BcmPassDoorSwtSts_sig
  (void);

#define Rte_Write_VeOUT_REL_BcmLeReDoorSwtSts_sig_VeOUT_REL_BcmLeReDoorSwtSts_sig Rte_Write_REL_VeOUT_REL_BcmLeReDoorSwtSts_sig_VeOUT_REL_BcmLeReDoorSwtSts_sig

Std_ReturnType
  Rte_Write_VeOUT_REL_BcmLeReDoorSwtSts_sig_VeOUT_REL_BcmLeReDoorSwtSts_sig
  (UInt8 u);

#define Rte_Invalidate_VeOUT_REL_BcmLeReDoorSwtSts_sig_VeOUT_REL_BcmLeReDoorSwtSts_sig Rte_Invalidate_REL_VeOUT_REL_BcmLeReDoorSwtSts_sig_VeOUT_REL_BcmLeReDoorSwtSts_sig

Std_ReturnType
  Rte_Invalidate_VeOUT_REL_BcmLeReDoorSwtSts_sig_VeOUT_REL_BcmLeReDoorSwtSts_sig
  (void);

#define Rte_Write_VeOUT_REL_BcmRiReDoorSwtSts_sig_VeOUT_REL_BcmRiReDoorSwtSts_sig Rte_Write_REL_VeOUT_REL_BcmRiReDoorSwtSts_sig_VeOUT_REL_BcmRiReDoorSwtSts_sig

Std_ReturnType
  Rte_Write_VeOUT_REL_BcmRiReDoorSwtSts_sig_VeOUT_REL_BcmRiReDoorSwtSts_sig
  (UInt8 u);

#define Rte_Invalidate_VeOUT_REL_BcmRiReDoorSwtSts_sig_VeOUT_REL_BcmRiReDoorSwtSts_sig Rte_Invalidate_REL_VeOUT_REL_BcmRiReDoorSwtSts_sig_VeOUT_REL_BcmRiReDoorSwtSts_sig

Std_ReturnType
  Rte_Invalidate_VeOUT_REL_BcmRiReDoorSwtSts_sig_VeOUT_REL_BcmRiReDoorSwtSts_sig
  (void);

#define Rte_Write_VeOUT_REL_BdcLFDoorRatSts_sig_VeOUT_REL_BdcLFDoorRatSts_sig Rte_Write_REL_VeOUT_REL_BdcLFDoorRatSts_sig_VeOUT_REL_BdcLFDoorRatSts_sig

Std_ReturnType
  Rte_Write_VeOUT_REL_BdcLFDoorRatSts_sig_VeOUT_REL_BdcLFDoorRatSts_sig(UInt8 u);

#define Rte_Invalidate_VeOUT_REL_BdcLFDoorRatSts_sig_VeOUT_REL_BdcLFDoorRatSts_sig Rte_Invalidate_REL_VeOUT_REL_BdcLFDoorRatSts_sig_VeOUT_REL_BdcLFDoorRatSts_sig

Std_ReturnType
  Rte_Invalidate_VeOUT_REL_BdcLFDoorRatSts_sig_VeOUT_REL_BdcLFDoorRatSts_sig
  (void);

#define Rte_Write_VeOUT_REL_BdcRFDoorRatSts_sig_VeOUT_REL_BdcRFDoorRatSts_sig Rte_Write_REL_VeOUT_REL_BdcRFDoorRatSts_sig_VeOUT_REL_BdcRFDoorRatSts_sig

Std_ReturnType
  Rte_Write_VeOUT_REL_BdcRFDoorRatSts_sig_VeOUT_REL_BdcRFDoorRatSts_sig(UInt8 u);

#define Rte_Invalidate_VeOUT_REL_BdcRFDoorRatSts_sig_VeOUT_REL_BdcRFDoorRatSts_sig Rte_Invalidate_REL_VeOUT_REL_BdcRFDoorRatSts_sig_VeOUT_REL_BdcRFDoorRatSts_sig

Std_ReturnType
  Rte_Invalidate_VeOUT_REL_BdcRFDoorRatSts_sig_VeOUT_REL_BdcRFDoorRatSts_sig
  (void);

#define Rte_Write_VeOUT_REL_BdcLRDoorRatSts_sig_VeOUT_REL_BdcLRDoorRatSts_sig Rte_Write_REL_VeOUT_REL_BdcLRDoorRatSts_sig_VeOUT_REL_BdcLRDoorRatSts_sig

Std_ReturnType
  Rte_Write_VeOUT_REL_BdcLRDoorRatSts_sig_VeOUT_REL_BdcLRDoorRatSts_sig(UInt8 u);

#define Rte_Invalidate_VeOUT_REL_BdcLRDoorRatSts_sig_VeOUT_REL_BdcLRDoorRatSts_sig Rte_Invalidate_REL_VeOUT_REL_BdcLRDoorRatSts_sig_VeOUT_REL_BdcLRDoorRatSts_sig

Std_ReturnType
  Rte_Invalidate_VeOUT_REL_BdcLRDoorRatSts_sig_VeOUT_REL_BdcLRDoorRatSts_sig
  (void);

#define Rte_Write_VeOUT_REL_BdcRRDoorRatSts_sig_VeOUT_REL_BdcRRDoorRatSts_sig Rte_Write_REL_VeOUT_REL_BdcRRDoorRatSts_sig_VeOUT_REL_BdcRRDoorRatSts_sig

Std_ReturnType
  Rte_Write_VeOUT_REL_BdcRRDoorRatSts_sig_VeOUT_REL_BdcRRDoorRatSts_sig(UInt8 u);

#define Rte_Invalidate_VeOUT_REL_BdcRRDoorRatSts_sig_VeOUT_REL_BdcRRDoorRatSts_sig Rte_Invalidate_REL_VeOUT_REL_BdcRRDoorRatSts_sig_VeOUT_REL_BdcRRDoorRatSts_sig

Std_ReturnType
  Rte_Invalidate_VeOUT_REL_BdcRRDoorRatSts_sig_VeOUT_REL_BdcRRDoorRatSts_sig
  (void);

#define Rte_Write_VbOUT_REL_BcmDrvrDoorHandleReq_flg_VbOUT_REL_BcmDrvrDoorHandleReq_flg Rte_Write_REL_VbOUT_REL_BcmDrvrDoorHandleReq_flg_VbOUT_REL_BcmDrvrDoorHandleReq_flg

Std_ReturnType
  Rte_Write_VbOUT_REL_BcmDrvrDoorHandleReq_flg_VbOUT_REL_BcmDrvrDoorHandleReq_flg
  (Boolean u);

#define Rte_Invalidate_VbOUT_REL_BcmDrvrDoorHandleReq_flg_VbOUT_REL_BcmDrvrDoorHandleReq_flg Rte_Invalidate_REL_VbOUT_REL_BcmDrvrDoorHandleReq_flg_VbOUT_REL_BcmDrvrDoorHandleReq_flg

Std_ReturnType
  Rte_Invalidate_VbOUT_REL_BcmDrvrDoorHandleReq_flg_VbOUT_REL_BcmDrvrDoorHandleReq_flg
  (void);

#define Rte_Write_VbOUT_REL_BcmPassDoorHandleReq_flg_VbOUT_REL_BcmPassDoorHandleReq_flg Rte_Write_REL_VbOUT_REL_BcmPassDoorHandleReq_flg_VbOUT_REL_BcmPassDoorHandleReq_flg

Std_ReturnType
  Rte_Write_VbOUT_REL_BcmPassDoorHandleReq_flg_VbOUT_REL_BcmPassDoorHandleReq_flg
  (Boolean u);

#define Rte_Invalidate_VbOUT_REL_BcmPassDoorHandleReq_flg_VbOUT_REL_BcmPassDoorHandleReq_flg Rte_Invalidate_REL_VbOUT_REL_BcmPassDoorHandleReq_flg_VbOUT_REL_BcmPassDoorHandleReq_flg

Std_ReturnType
  Rte_Invalidate_VbOUT_REL_BcmPassDoorHandleReq_flg_VbOUT_REL_BcmPassDoorHandleReq_flg
  (void);

#define Rte_Write_VbOUT_REL_BcmLeReDoorHandleReq_flg_VbOUT_REL_BcmLeReDoorHandleReq_flg Rte_Write_REL_VbOUT_REL_BcmLeReDoorHandleReq_flg_VbOUT_REL_BcmLeReDoorHandleReq_flg

Std_ReturnType
  Rte_Write_VbOUT_REL_BcmLeReDoorHandleReq_flg_VbOUT_REL_BcmLeReDoorHandleReq_flg
  (Boolean u);

#define Rte_Invalidate_VbOUT_REL_BcmLeReDoorHandleReq_flg_VbOUT_REL_BcmLeReDoorHandleReq_flg Rte_Invalidate_REL_VbOUT_REL_BcmLeReDoorHandleReq_flg_VbOUT_REL_BcmLeReDoorHandleReq_flg

Std_ReturnType
  Rte_Invalidate_VbOUT_REL_BcmLeReDoorHandleReq_flg_VbOUT_REL_BcmLeReDoorHandleReq_flg
  (void);

#define Rte_Write_VbOUT_REL_BcmBcmRiReDoorHandleReq_flg_VbOUT_REL_BcmBcmRiReDoorHandleReq_flg Rte_Write_REL_VbOUT_REL_BcmBcmRiReDoorHandleReq_flg_VbOUT_REL_BcmBcmRiReDoorHandleReq_flg

Std_ReturnType
  Rte_Write_VbOUT_REL_BcmBcmRiReDoorHandleReq_flg_VbOUT_REL_BcmBcmRiReDoorHandleReq_flg
  (Boolean u);

#define Rte_Invalidate_VbOUT_REL_BcmBcmRiReDoorHandleReq_flg_VbOUT_REL_BcmBcmRiReDoorHandleReq_flg Rte_Invalidate_REL_VbOUT_REL_BcmBcmRiReDoorHandleReq_flg_VbOUT_REL_BcmBcmRiReDoorHandleReq_flg

Std_ReturnType
  Rte_Invalidate_VbOUT_REL_BcmBcmRiReDoorHandleReq_flg_VbOUT_REL_BcmBcmRiReDoorHandleReq_flg
  (void);

#define Rte_Write_VbOUT_REL_FLDoorHndlBtnSig_flg_VbOUT_REL_FLDoorHndlBtnSig_flg Rte_Write_REL_VbOUT_REL_FLDoorHndlBtnSig_flg_VbOUT_REL_FLDoorHndlBtnSig_flg

Std_ReturnType
  Rte_Write_VbOUT_REL_FLDoorHndlBtnSig_flg_VbOUT_REL_FLDoorHndlBtnSig_flg
  (Boolean u);

#define Rte_Invalidate_VbOUT_REL_FLDoorHndlBtnSig_flg_VbOUT_REL_FLDoorHndlBtnSig_flg Rte_Invalidate_REL_VbOUT_REL_FLDoorHndlBtnSig_flg_VbOUT_REL_FLDoorHndlBtnSig_flg

Std_ReturnType
  Rte_Invalidate_VbOUT_REL_FLDoorHndlBtnSig_flg_VbOUT_REL_FLDoorHndlBtnSig_flg
  (void);

#define Rte_Write_VbOUT_REL_FRDoorHndlBtnSig_flg_VbOUT_REL_FRDoorHndlBtnSig_flg Rte_Write_REL_VbOUT_REL_FRDoorHndlBtnSig_flg_VbOUT_REL_FRDoorHndlBtnSig_flg

Std_ReturnType
  Rte_Write_VbOUT_REL_FRDoorHndlBtnSig_flg_VbOUT_REL_FRDoorHndlBtnSig_flg
  (Boolean u);

#define Rte_Invalidate_VbOUT_REL_FRDoorHndlBtnSig_flg_VbOUT_REL_FRDoorHndlBtnSig_flg Rte_Invalidate_REL_VbOUT_REL_FRDoorHndlBtnSig_flg_VbOUT_REL_FRDoorHndlBtnSig_flg

Std_ReturnType
  Rte_Invalidate_VbOUT_REL_FRDoorHndlBtnSig_flg_VbOUT_REL_FRDoorHndlBtnSig_flg
  (void);

#define Rte_Write_VbOUT_REL_RLDoorHndlBtnSig_flg_VbOUT_REL_RLDoorHndlBtnSig_flg Rte_Write_REL_VbOUT_REL_RLDoorHndlBtnSig_flg_VbOUT_REL_RLDoorHndlBtnSig_flg

Std_ReturnType
  Rte_Write_VbOUT_REL_RLDoorHndlBtnSig_flg_VbOUT_REL_RLDoorHndlBtnSig_flg
  (Boolean u);

#define Rte_Invalidate_VbOUT_REL_RLDoorHndlBtnSig_flg_VbOUT_REL_RLDoorHndlBtnSig_flg Rte_Invalidate_REL_VbOUT_REL_RLDoorHndlBtnSig_flg_VbOUT_REL_RLDoorHndlBtnSig_flg

Std_ReturnType
  Rte_Invalidate_VbOUT_REL_RLDoorHndlBtnSig_flg_VbOUT_REL_RLDoorHndlBtnSig_flg
  (void);

#define Rte_Write_VbOUT_REL_RRDoorHndlBtnSig_flg_VbOUT_REL_RRDoorHndlBtnSig_flg Rte_Write_REL_VbOUT_REL_RRDoorHndlBtnSig_flg_VbOUT_REL_RRDoorHndlBtnSig_flg

Std_ReturnType
  Rte_Write_VbOUT_REL_RRDoorHndlBtnSig_flg_VbOUT_REL_RRDoorHndlBtnSig_flg
  (Boolean u);

#define Rte_Invalidate_VbOUT_REL_RRDoorHndlBtnSig_flg_VbOUT_REL_RRDoorHndlBtnSig_flg Rte_Invalidate_REL_VbOUT_REL_RRDoorHndlBtnSig_flg_VbOUT_REL_RRDoorHndlBtnSig_flg

Std_ReturnType
  Rte_Invalidate_VbOUT_REL_RRDoorHndlBtnSig_flg_VbOUT_REL_RRDoorHndlBtnSig_flg
  (void);

#define Rte_Write_VbOUT_REL_BdcDrvrDoorLockOpenReq_flg_VbOUT_REL_BdcDrvrDoorLockOpenReq_flg Rte_Write_REL_VbOUT_REL_BdcDrvrDoorLockOpenReq_flg_VbOUT_REL_BdcDrvrDoorLockOpenReq_flg

Std_ReturnType
  Rte_Write_VbOUT_REL_BdcDrvrDoorLockOpenReq_flg_VbOUT_REL_BdcDrvrDoorLockOpenReq_flg
  (Boolean u);

#define Rte_Invalidate_VbOUT_REL_BdcDrvrDoorLockOpenReq_flg_VbOUT_REL_BdcDrvrDoorLockOpenReq_flg Rte_Invalidate_REL_VbOUT_REL_BdcDrvrDoorLockOpenReq_flg_VbOUT_REL_BdcDrvrDoorLockOpenReq_flg

Std_ReturnType
  Rte_Invalidate_VbOUT_REL_BdcDrvrDoorLockOpenReq_flg_VbOUT_REL_BdcDrvrDoorLockOpenReq_flg
  (void);

#define Rte_Write_VbOUT_REL_FLDoorMotorA_flg_VbOUT_REL_FLDoorMotorA_flg Rte_Write_REL_VbOUT_REL_FLDoorMotorA_flg_VbOUT_REL_FLDoorMotorA_flg

Std_ReturnType Rte_Write_VbOUT_REL_FLDoorMotorA_flg_VbOUT_REL_FLDoorMotorA_flg
  (Boolean u);

#define Rte_Invalidate_VbOUT_REL_FLDoorMotorA_flg_VbOUT_REL_FLDoorMotorA_flg Rte_Invalidate_REL_VbOUT_REL_FLDoorMotorA_flg_VbOUT_REL_FLDoorMotorA_flg

Std_ReturnType
  Rte_Invalidate_VbOUT_REL_FLDoorMotorA_flg_VbOUT_REL_FLDoorMotorA_flg(void);

#define Rte_Write_VbOUT_REL_FLDoorMotorB_flg_VbOUT_REL_FLDoorMotorB_flg Rte_Write_REL_VbOUT_REL_FLDoorMotorB_flg_VbOUT_REL_FLDoorMotorB_flg

Std_ReturnType Rte_Write_VbOUT_REL_FLDoorMotorB_flg_VbOUT_REL_FLDoorMotorB_flg
  (Boolean u);

#define Rte_Invalidate_VbOUT_REL_FLDoorMotorB_flg_VbOUT_REL_FLDoorMotorB_flg Rte_Invalidate_REL_VbOUT_REL_FLDoorMotorB_flg_VbOUT_REL_FLDoorMotorB_flg

Std_ReturnType
  Rte_Invalidate_VbOUT_REL_FLDoorMotorB_flg_VbOUT_REL_FLDoorMotorB_flg(void);

#define Rte_Write_VbOUT_REL_FRDoorMotorA_flg_VbOUT_REL_FRDoorMotorA_flg Rte_Write_REL_VbOUT_REL_FRDoorMotorA_flg_VbOUT_REL_FRDoorMotorA_flg

Std_ReturnType Rte_Write_VbOUT_REL_FRDoorMotorA_flg_VbOUT_REL_FRDoorMotorA_flg
  (Boolean u);

#define Rte_Invalidate_VbOUT_REL_FRDoorMotorA_flg_VbOUT_REL_FRDoorMotorA_flg Rte_Invalidate_REL_VbOUT_REL_FRDoorMotorA_flg_VbOUT_REL_FRDoorMotorA_flg

Std_ReturnType
  Rte_Invalidate_VbOUT_REL_FRDoorMotorA_flg_VbOUT_REL_FRDoorMotorA_flg(void);

#define Rte_Write_VbOUT_REL_FRDoorMotorB_flg_VbOUT_REL_FRDoorMotorB_flg Rte_Write_REL_VbOUT_REL_FRDoorMotorB_flg_VbOUT_REL_FRDoorMotorB_flg

Std_ReturnType Rte_Write_VbOUT_REL_FRDoorMotorB_flg_VbOUT_REL_FRDoorMotorB_flg
  (Boolean u);

#define Rte_Invalidate_VbOUT_REL_FRDoorMotorB_flg_VbOUT_REL_FRDoorMotorB_flg Rte_Invalidate_REL_VbOUT_REL_FRDoorMotorB_flg_VbOUT_REL_FRDoorMotorB_flg

Std_ReturnType
  Rte_Invalidate_VbOUT_REL_FRDoorMotorB_flg_VbOUT_REL_FRDoorMotorB_flg(void);

#define Rte_Write_VbOUT_REL_RLDoorMotorA_flg_VbOUT_REL_RLDoorMotorA_flg Rte_Write_REL_VbOUT_REL_RLDoorMotorA_flg_VbOUT_REL_RLDoorMotorA_flg

Std_ReturnType Rte_Write_VbOUT_REL_RLDoorMotorA_flg_VbOUT_REL_RLDoorMotorA_flg
  (Boolean u);

#define Rte_Invalidate_VbOUT_REL_RLDoorMotorA_flg_VbOUT_REL_RLDoorMotorA_flg Rte_Invalidate_REL_VbOUT_REL_RLDoorMotorA_flg_VbOUT_REL_RLDoorMotorA_flg

Std_ReturnType
  Rte_Invalidate_VbOUT_REL_RLDoorMotorA_flg_VbOUT_REL_RLDoorMotorA_flg(void);

#define Rte_Write_VbOUT_REL_RLDoorMotorB_flg_VbOUT_REL_RLDoorMotorB_flg Rte_Write_REL_VbOUT_REL_RLDoorMotorB_flg_VbOUT_REL_RLDoorMotorB_flg

Std_ReturnType Rte_Write_VbOUT_REL_RLDoorMotorB_flg_VbOUT_REL_RLDoorMotorB_flg
  (Boolean u);

#define Rte_Invalidate_VbOUT_REL_RLDoorMotorB_flg_VbOUT_REL_RLDoorMotorB_flg Rte_Invalidate_REL_VbOUT_REL_RLDoorMotorB_flg_VbOUT_REL_RLDoorMotorB_flg

Std_ReturnType
  Rte_Invalidate_VbOUT_REL_RLDoorMotorB_flg_VbOUT_REL_RLDoorMotorB_flg(void);

#define Rte_Write_VbOUT_REL_RRDoorMotorA_flg_VbOUT_REL_RRDoorMotorA_flg Rte_Write_REL_VbOUT_REL_RRDoorMotorA_flg_VbOUT_REL_RRDoorMotorA_flg

Std_ReturnType Rte_Write_VbOUT_REL_RRDoorMotorA_flg_VbOUT_REL_RRDoorMotorA_flg
  (Boolean u);

#define Rte_Invalidate_VbOUT_REL_RRDoorMotorA_flg_VbOUT_REL_RRDoorMotorA_flg Rte_Invalidate_REL_VbOUT_REL_RRDoorMotorA_flg_VbOUT_REL_RRDoorMotorA_flg

Std_ReturnType
  Rte_Invalidate_VbOUT_REL_RRDoorMotorA_flg_VbOUT_REL_RRDoorMotorA_flg(void);

#define Rte_Write_VbOUT_REL_RRDoorMotorB_flg_VbOUT_REL_RRDoorMotorB_flg Rte_Write_REL_VbOUT_REL_RRDoorMotorB_flg_VbOUT_REL_RRDoorMotorB_flg

Std_ReturnType Rte_Write_VbOUT_REL_RRDoorMotorB_flg_VbOUT_REL_RRDoorMotorB_flg
  (Boolean u);

#define Rte_Invalidate_VbOUT_REL_RRDoorMotorB_flg_VbOUT_REL_RRDoorMotorB_flg Rte_Invalidate_REL_VbOUT_REL_RRDoorMotorB_flg_VbOUT_REL_RRDoorMotorB_flg

Std_ReturnType
  Rte_Invalidate_VbOUT_REL_RRDoorMotorB_flg_VbOUT_REL_RRDoorMotorB_flg(void);

#define Rte_Write_VeOUT_REL_DLKReqUnlock_sig_VeOUT_REL_DLKReqUnlock_sig Rte_Write_REL_VeOUT_REL_DLKReqUnlock_sig_VeOUT_REL_DLKReqUnlock_sig

Std_ReturnType Rte_Write_VeOUT_REL_DLKReqUnlock_sig_VeOUT_REL_DLKReqUnlock_sig
  (UInt8 u);

#define Rte_Invalidate_VeOUT_REL_DLKReqUnlock_sig_VeOUT_REL_DLKReqUnlock_sig Rte_Invalidate_REL_VeOUT_REL_DLKReqUnlock_sig_VeOUT_REL_DLKReqUnlock_sig

Std_ReturnType
  Rte_Invalidate_VeOUT_REL_DLKReqUnlock_sig_VeOUT_REL_DLKReqUnlock_sig(void);

#define Rte_Write_VbOUT_REL_FLDoorRlsReq_flg_VbOUT_REL_FLDoorRlsReq_flg Rte_Write_REL_VbOUT_REL_FLDoorRlsReq_flg_VbOUT_REL_FLDoorRlsReq_flg

Std_ReturnType Rte_Write_VbOUT_REL_FLDoorRlsReq_flg_VbOUT_REL_FLDoorRlsReq_flg
  (Boolean u);

#define Rte_Invalidate_VbOUT_REL_FLDoorRlsReq_flg_VbOUT_REL_FLDoorRlsReq_flg Rte_Invalidate_REL_VbOUT_REL_FLDoorRlsReq_flg_VbOUT_REL_FLDoorRlsReq_flg

Std_ReturnType
  Rte_Invalidate_VbOUT_REL_FLDoorRlsReq_flg_VbOUT_REL_FLDoorRlsReq_flg(void);

#define Rte_Write_VbOUT_REL_FRDoorRlsReq_flg_VbOUT_REL_FRDoorRlsReq_flg Rte_Write_REL_VbOUT_REL_FRDoorRlsReq_flg_VbOUT_REL_FRDoorRlsReq_flg

Std_ReturnType Rte_Write_VbOUT_REL_FRDoorRlsReq_flg_VbOUT_REL_FRDoorRlsReq_flg
  (Boolean u);

#define Rte_Invalidate_VbOUT_REL_FRDoorRlsReq_flg_VbOUT_REL_FRDoorRlsReq_flg Rte_Invalidate_REL_VbOUT_REL_FRDoorRlsReq_flg_VbOUT_REL_FRDoorRlsReq_flg

Std_ReturnType
  Rte_Invalidate_VbOUT_REL_FRDoorRlsReq_flg_VbOUT_REL_FRDoorRlsReq_flg(void);

#define Rte_Write_VbOUT_REL_RLDoorRlsReq_flg_VbOUT_REL_RLDoorRlsReq_flg Rte_Write_REL_VbOUT_REL_RLDoorRlsReq_flg_VbOUT_REL_RLDoorRlsReq_flg

Std_ReturnType Rte_Write_VbOUT_REL_RLDoorRlsReq_flg_VbOUT_REL_RLDoorRlsReq_flg
  (Boolean u);

#define Rte_Invalidate_VbOUT_REL_RLDoorRlsReq_flg_VbOUT_REL_RLDoorRlsReq_flg Rte_Invalidate_REL_VbOUT_REL_RLDoorRlsReq_flg_VbOUT_REL_RLDoorRlsReq_flg

Std_ReturnType
  Rte_Invalidate_VbOUT_REL_RLDoorRlsReq_flg_VbOUT_REL_RLDoorRlsReq_flg(void);

#define Rte_Write_VbOUT_REL_RRDoorRlsReq_flg_VbOUT_REL_RRDoorRlsReq_flg Rte_Write_REL_VbOUT_REL_RRDoorRlsReq_flg_VbOUT_REL_RRDoorRlsReq_flg

Std_ReturnType Rte_Write_VbOUT_REL_RRDoorRlsReq_flg_VbOUT_REL_RRDoorRlsReq_flg
  (Boolean u);

#define Rte_Invalidate_VbOUT_REL_RRDoorRlsReq_flg_VbOUT_REL_RRDoorRlsReq_flg Rte_Invalidate_REL_VbOUT_REL_RRDoorRlsReq_flg_VbOUT_REL_RRDoorRlsReq_flg

Std_ReturnType
  Rte_Invalidate_VbOUT_REL_RRDoorRlsReq_flg_VbOUT_REL_RRDoorRlsReq_flg(void);

#define Rte_Write_VeOUT_REL_FLDoorMotorSts_sig_VeOUT_REL_FLDoorMotorSts_sig Rte_Write_REL_VeOUT_REL_FLDoorMotorSts_sig_VeOUT_REL_FLDoorMotorSts_sig

Std_ReturnType
  Rte_Write_VeOUT_REL_FLDoorMotorSts_sig_VeOUT_REL_FLDoorMotorSts_sig(UInt8 u);

#define Rte_Invalidate_VeOUT_REL_FLDoorMotorSts_sig_VeOUT_REL_FLDoorMotorSts_sig Rte_Invalidate_REL_VeOUT_REL_FLDoorMotorSts_sig_VeOUT_REL_FLDoorMotorSts_sig

Std_ReturnType
  Rte_Invalidate_VeOUT_REL_FLDoorMotorSts_sig_VeOUT_REL_FLDoorMotorSts_sig(void);

#define Rte_Write_VeOUT_REL_FRDoorMotorSts_sig_VeOUT_REL_FRDoorMotorSts_sig Rte_Write_REL_VeOUT_REL_FRDoorMotorSts_sig_VeOUT_REL_FRDoorMotorSts_sig

Std_ReturnType
  Rte_Write_VeOUT_REL_FRDoorMotorSts_sig_VeOUT_REL_FRDoorMotorSts_sig(UInt8 u);

#define Rte_Invalidate_VeOUT_REL_FRDoorMotorSts_sig_VeOUT_REL_FRDoorMotorSts_sig Rte_Invalidate_REL_VeOUT_REL_FRDoorMotorSts_sig_VeOUT_REL_FRDoorMotorSts_sig

Std_ReturnType
  Rte_Invalidate_VeOUT_REL_FRDoorMotorSts_sig_VeOUT_REL_FRDoorMotorSts_sig(void);

#define Rte_Write_VeOUT_REL_RLDoorMotorSts_sig_VeOUT_REL_RLDoorMotorSts_sig Rte_Write_REL_VeOUT_REL_RLDoorMotorSts_sig_VeOUT_REL_RLDoorMotorSts_sig

Std_ReturnType
  Rte_Write_VeOUT_REL_RLDoorMotorSts_sig_VeOUT_REL_RLDoorMotorSts_sig(UInt8 u);

#define Rte_Invalidate_VeOUT_REL_RLDoorMotorSts_sig_VeOUT_REL_RLDoorMotorSts_sig Rte_Invalidate_REL_VeOUT_REL_RLDoorMotorSts_sig_VeOUT_REL_RLDoorMotorSts_sig

Std_ReturnType
  Rte_Invalidate_VeOUT_REL_RLDoorMotorSts_sig_VeOUT_REL_RLDoorMotorSts_sig(void);

#define Rte_Write_VeOUT_REL_RRDoorMotorSts_sig_VeOUT_REL_RRDoorMotorSts_sig Rte_Write_REL_VeOUT_REL_RRDoorMotorSts_sig_VeOUT_REL_RRDoorMotorSts_sig

Std_ReturnType
  Rte_Write_VeOUT_REL_RRDoorMotorSts_sig_VeOUT_REL_RRDoorMotorSts_sig(UInt8 u);

#define Rte_Invalidate_VeOUT_REL_RRDoorMotorSts_sig_VeOUT_REL_RRDoorMotorSts_sig Rte_Invalidate_REL_VeOUT_REL_RRDoorMotorSts_sig_VeOUT_REL_RRDoorMotorSts_sig

Std_ReturnType
  Rte_Invalidate_VeOUT_REL_RRDoorMotorSts_sig_VeOUT_REL_RRDoorMotorSts_sig(void);

/* Entry point functions */
extern FUNC(void, REL_CODE) REL_Init(void);
extern FUNC(void, REL_CODE) REL_Step(void);

#endif
